version: '3.8'

services:
  postgres:
    container_name: ms-user
    image: postgres:latest
    environment:
      POSTGRES_DB: ms_user_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ingress
    ports:
      - "1111:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: